[package]
name = "rust_game_server"
version = "0.1.0"
authors = ["Victor Koenders <victor.koenders@gmail.com>"]

[dependencies]
shared = { path = "../shared", version = "*" }
time = "*"
bincode = "*"
rustc-serialize = "*"